name: angel_multiserver
description: Support for running Angel applications across multiple servers.
environment:
  sdk: ">=1.19.0"
version: 1.0.0-beta
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_multiserver
dependencies:
  angel_framework: ^1.0.0-dev
  glob: ^1.0.0
  memcached_client: ^0.5.3
  mongo_dart: ^0.2.10
  random_string: ^0.0.1
  redis_client: ^0.1.16
dev_dependencies:
  angel_compress: ^1.0.0-dev
  angel_diagnostics: ^1.0.0-dev
  angel_errors: ^1.0.0-dev
  angel_static: ^1.1.0-dev
  http: ^0.11.3
  test: ^0.12.15