name: angel_multiserver
description: Framework-agnostic load balancer, as well as Angel-specific scaling support.
environment:
  sdk: ">=1.19.0"
version: 1.0.7
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_multiserver
dependencies:
  angel_framework: ^1.0.0-dev
  angel_websocket: ^1.0.0
  glob: ^1.0.0
  memcached_client: ^0.5.3
  mongo_dart: ^0.2.10
  pool: ^1.3.0
  random_string: ^0.0.1
  redis_client: ^0.1.16
dev_dependencies:
  angel_compress: ^1.0.0
  angel_diagnostics: ^1.0.0-dev
  angel_errors: ^1.0.0-dev
  angel_static: ^1.1.0
  http: ^0.11.3
  test: ^0.12.15