name: angel_multiserver
description: Support for running Angel applications across multiple servers.
environment:
  sdk: ">=1.19.0"
version: 1.0.0-dev
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_multiserver
dependencies:
  angel_framework: ^1.0.0-dev
  memcached_client: ^0.5.3
  mongo_dart: ^0.2.10
  redis_client: ^0.1.16
dev_dependencies:
  angel_diagnostics: ^1.0.0-dev
  http: ^0.11.3
  test: ^0.12.15